config/routes.rb
Rails.application.routes.draw do
  
  get '/profile' => 'home#profile'

  get '/' => 'home#index'
  get '/home' => 'home#index'  
  get '/profile' => 'home#profile'
  post '/profile/links/add' => 'home#add_link'
  post '/profile/education/add' => 'home#add_education'
  post '/profile/skill/add' => 'home#add_skill'
  post '/profile/about/add' => 'home#add_about'
  get '/profile/edit' => 'home#edit' 
  post '/profile/edit/confirm' => 'home#confirm_edit'
  post '/profile/edit/delete' => 'home#delete'
  get '/sample1' => 'home#sample1'
  get '/sample2' => 'home#sample2'
  get '/templates' => 'home#templates'
  resources :personal_details

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  

end

app/models/personal_detail.rb
class PersonalDetail < ActiveRecord::Base
end

app/controllers/personal_details_controller.rb
class PersonalDetailsController < ApplicationController
  before_action :set_personal_detail, only: [:show, :edit, :update, :destroy]

  # GET /personal_details
  # GET /personal_details.json
  def index
    @personal_details = PersonalDetail.all
  end

  # GET /personal_details/1
  # GET /personal_details/1.json
  def show
  end

  # GET /personal_details/new
  def new
    @personal_detail = PersonalDetail.new
  end

  # GET /personal_details/1/edit
  def edit
  end

  # POST /personal_details
  # POST /personal_details.json
  def create
    @personal_detail = PersonalDetail.new(personal_detail_params)
    @personal_detail.user_id = current_user.id
    if(params[:personal_detail][:photo])
      filename = params[:personal_detail][:photo].original_filename
      file = @personal_detail.user_id.to_s + "_" + filename
      temp_file = params[:personal_detail][:photo]
      @personal_detail.photo = filename
      File.open(Rails.root.join('public', 'uploads', 'users', file), 'wb') do |f|
          f.write(temp_file.read)
      end
    end
    respond_to do |format|
      if @personal_detail.save
        format.html { redirect_to @personal_detail, notice: 'Personal detail was successfully created.' }
        format.json { render :show, status: :created, location: @personal_detail }
      else
        format.html { render :new }
        format.json { render json: @personal_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_details/1
  # PATCH/PUT /personal_details/1.json
  def update
    respond_to do |format|
      if @personal_detail.update(personal_detail_params)
        if(params[:personal_detail][:photo])
          filename = params[:personal_detail][:photo].original_filename
          file = @personal_detail.user_id.to_s + "_" + filename
          old_file = @personal_detail.user_id.to_s + "_" + @personal_detail.photo
          temp_file = params[:personal_detail][:photo]
          @personal_detail.photo = filename
          
          if(@personal_detail.photo)
            File.delete(Rails.root.join('public', 'uploads', 'users', old_file))
          end

          File.open(Rails.root.join('public', 'uploads', 'users', file), 'wb') do |f|
            f.write(temp_file.read)
          end
        end
        @personal_detail.save
        format.html { redirect_to @personal_detail, notice: 'Personal detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_detail }
      else
        format.html { render :edit }
        format.json { render json: @personal_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_details/1
  # DELETE /personal_details/1.json
  def destroy
    @personal_detail.destroy
    respond_to do |format|
      format.html { redirect_to personal_details_url, notice: 'Personal detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_detail
      @personal_detail = PersonalDetail.where(:user_id => current_user.id).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_detail_params
      params.require(:personal_detail).permit(:name, :dob, :phone, :address, :city, :pin, :designation, :description)
    end
end

app/helpers/personal_details_helper.rb
module PersonalDetailsHelper
end

app/views/personal_details/_form.html.erb
<%= form_for(@personal_detail) do |f| %>
  <% if @personal_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personal_detail.errors.count, "error") %> prohibited this personal_detail from being saved:</h2>

      <ul>
      <% @personal_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :pin %><br>
    <%= f.text_field :pin %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :designation %><br>
    <%= f.file_field :designation %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.file_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personal_details/edit.html.erb
<h1>Editing Personal Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @personal_detail %> |
<%= link_to 'Back', personal_details_path %>

app/views/personal_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personal Details</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Dob</th>
      <th>Phone</th>
      <th>Address</th>
      <th>City</th>
      <th>Pin</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personal_details.each do |personal_detail| %>
      <tr>
        <td><%= personal_detail.user_id %></td>
        <td><%= personal_detail.name %></td>
        <td><%= personal_detail.dob %></td>
        <td><%= personal_detail.phone %></td>
        <td><%= personal_detail.address %></td>
        <td><%= personal_detail.city %></td>
        <td><%= personal_detail.pin %></td>
        <td><%= personal_detail.designation %></td>
        <td><%= personal_detail.description %></td>
        <td><%= personal_detail.photo %></td>
        <td><%= link_to 'Show', personal_detail %></td>
        <td><%= link_to 'Edit', edit_personal_detail_path(personal_detail) %></td>
        <td><%= link_to 'Destroy', personal_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personal detail', new_personal_detail_path %>

app/views/personal_details/new.html.erb
<h1>New Personal Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', personal_details_path %>

app/views/personal_details/show.html.erb
<p id="notice"><%= notice %></p>

<% if @personal_detail %>
    <div class="profile">
      <div class="avatar">
        <img src="<%= avatar %>" onerror="this.onerror=null; this.src='/images/male.png';">
      </div>
      <div class="details">
        <div class="content">
          <div class="name">
            <span> <%= @personal_detail.name %> </span>
          </div>
          <div class="designation">
            <span> Student @DTU </span>
          </div>
        </div>
        <div class="profile_links">
          <div id="edit_profile">
            <%= link_to edit_personal_detail_path(@personal_detail) do %>
              <%= image_tag('/images/edit.svg', height: '30', width: '70') %>
            <% end %>
          </div>
          <div id="links">
            <img src="/images/facebook.ico">
            <img src="/images/github.png">
            <img src="/images/linkedin.png">
            <img src="/images/googleplus.ico">
          </div>
        </div>
      </div>
    </div>
    <p>
      <strong>Name:</strong>
      <%= @personal_detail.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= current_user.email %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @personal_detail.user_id %>
    </p>

    <p>
      <strong>Dob:</strong>
      <%= @personal_detail.dob %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @personal_detail.phone %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @personal_detail.address %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @personal_detail.city %>
    </p>

    <p>
      <strong>Pin:</strong>
      <%= @personal_detail.pin %>
    </p>

    <p>
      <strong>Designation:</strong>
      <%if @personal_detail.designation %>
        <%= @personal_detail.designation %>
      <%end%> 
    </p>

    <p>
      <strong>Description:</strong>
      <%= @personal_detail.description %>
    </p>

    <p>
      <strong>Photo:</strong>
      <%= @personal_detail.photo %>
    </p>

<% else %>
  <%= link_to 'Create Profile', new_personal_detail_path %>
<% end %>